default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

  # Note: we need at least one DB connection per puma thread or we'll run into the following:
  # ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds...)
  pool: <%= Integer(ENV['DB_POOL'] || Platform::Application::PUMA_MAX_THREADS || 5) %>


development:
  <<: *default
  database: platform_development

test:
  <<: *default
  database: platform_test

# Heroku takes care of the production database config, but if you want
# to add more options other than DATABASE_URL you can do so here.
production:
  <<: *default
  database: platform_production
  url: <%= ENV['DATABASE_URL'] %> # This is just so we can build in production mode on local dev. It's what Heroku does.
