production: &default
  maximum_unused_login_ticket_lifetime: 300
  maximum_unused_service_ticket_lifetime: 300
  maximum_session_lifetime: 172800
  maximum_remember_me_lifetime: 604800
  infoline: Powered by <a href="http://rubycas.github.com">RubyCAS-Server-Core</a>
  log:
    output:
    level: INFO
  public_site_domain: <%= ENV['PUBLIC_SITE_DOMAIN'] %>
  database: &default_db
    database: platform
    reconnect: true
    adapter: postgresql
    encoding: unicode
    host: <%= ENV['DATABASE_HOST'] %>
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
<% if ENV['BZ_AUTH_SERVER'] %>
  authenticator: &default_bz_auth
    class: BeyondZ::CustomAuthenticator
    source: beyondz.rb
    server: <%= ENV['BZ_AUTH_SERVER'] %>
    # We can override ssl, port, and self signed options for dev
    # The default is to use SSL.
    # ssl: false
    # port: 3001
    # allow_self_signed: true
<% else %>
  authenticator: &default_cas_auth
    class: BravenCAS::CustomAuthenticator
    source: cas_authenticator.rb
<% end %>

development:
  <<: *default
  log:
    output: 
    level: DEBUG
  public_site_domain: joinweb
  # this should be the *top* domain - so even for staging, it should be .join.bebraven.org stilldefault_service: http://canvasweb/login/cas
  cookie_domain: .localhost 
  theme: simple
  organization: Braven Docker SSO
  database:
    <<: *default_db
    database: platform_development
<% if ENV['BZ_AUTH_SERVER'] %>
  authenticator:
    <<: *default_bz_auth
    server: joinweb
    ssl: false
    port: 3001
    allow_self_signed: true
<% else %>
  authenticator:
    <<: *default_cas_auth
<% end %>

test:
  <<: *default
  log:
    output: 
    level: ERROR
  public_site_domain: joinweb
  # this should be the *top* domain - so even for staging, it should be .join.bebraven.org stilldefault_service: http://canvasweb/login/cas
  cookie_domain: .localhost 
  organization: "RSPEC-TEST"
  infoline: "This is an rspec test."  
  theme: simple
  database:
    <<: *default_db
    database: platform_test
<% if ENV['BZ_AUTH_SERVER'] %>
  authenticator:
    <<: *default_bz_auth
    server: joinweb
    ssl: false
    port: 3001
    allow_self_signed: true
<% else %>
  authenticator:
    <<: *default_cas_auth
<% end %>
  uri_path: /test
  disable_auto_migrations: true
  quiet: true
  default_locale: en
  enable_single_sign_out: true

  
