:max_retries: 0
:queues:
  - default
  - low_priority

# If you change the number of threads here make sure to also change the PUMA_MAX_THREADS
# number to match it in ENV and application.rb
:concurrency: <%= Integer(ENV['DB_POOL'] || ENV['SIDEKIQ_MAX_THREADS'] || 5) %>

# sidekiq-scheduler options
# See here for more info: https://github.com/moove-it/sidekiq-scheduler#schedule-types
:dynamic: true
:enabled: <%= ENV.fetch('SIDEKIQ_SCHEDULER_ENABLED') { true } %>
:schedule:
  sync_salesforce_changes:
    class: SyncSalesforceChangesJob
    description: "Syncs changes in Salesforce to Platform, Canvas, Zoom, etc. Note: Discord is handled separately."

    # Run every minute by default
    #
    # Note: technically, this value can take human readable formats, but we're using seconds
    # to be consistent with SALESFORCE_SYNC_MAX_DURATION.
    every: [<%= ENV.fetch('SALESFORCE_SYNC_EVERY') { '60' } %>]
