# frozen_string_literal: true

# This is a part of Braven Network.
# Please don't add features to Braven Network.
# This code should be considered unsupported. We want to remove it ASAP.
module ChampionsHelper
  INDUSTRIES_OPTIONS = [
    "Accounting",
    "Advertising",
    "Aerospace",
    "Banking",
    "Beauty / Cosmetics",
    "Biotechnology",
    "Business",
    "Chemical",
    "Communications",
    "Computer Engineering",
    "Computer Hardware",
    "Education",
    "Electronics",
    "Employment / Human Resources",
    "Energy",
    "Fashion",
    "Film",
    "Financial Services",
    "Fine Arts",
    "Food & Beverage",
    "Health",
    "Information Technology",
    "Insurance",
    "Journalism / News / Media",
    "Law",
    "Management / Strategic Consulting",
    "Manufacturing",
    "Marketing",
    "Medical Devices & Supplies",
    "Non-profit Management",
    "Performing Arts",
    "Pharmaceutical",
    "Public Administration",
    "Public Relations",
    "Publishing",
    "Racial Equity Consulting",
    "Real Estate",
    "Sports",
    "Technology",
    "Telecommunications",
    "Tourism",
    "Transportation / Travel",
    "Writing",
  ]

  STUDIES_OPTIONS = [
    "Accounting",
    "Actuarial Science",
    "Advertising",
    "Aerospace",
    "African American Studies",
    "African Studies",
    "Agriculture",
    "American Indian Studies",
    "American Studies",
    "Anatomy",
    "Animation",
    "Anthropology",
    "Archaeology",
    "Architecture",
    "Art History",
    "Asian American Studies",
    "Asian Studies",
    "Astronomy",
    "Banking",
    "Beauty / Cosmetics",
    "Biology",
    "Biomedical Engineering",
    "Biotechnology",
    "Business",
    "Cartography",
    "Chemical",
    "Chemical Engineering",
    "Chemistry",
    "Child Development",
    "Civil Engineering",
    "Cognitive Science",
    "Communications",
    "Computer Engineering",
    "Computer Hardware",
    "Computer Hardware Engineering",
    "Computer Science",
    "Construction Trades",
    "Creative Writing",
    "Criminal Justice",
    "Criminology",
    "Culinary Arts",
    "Dance",
    "Diversity Studies",
    "Ecology",
    "Economics",
    "Education",
    "Electrical Engineering",
    "Electronics",
    "Employment / Human Resources",
    "Energy",
    "English / Literature",
    "Environmental Studies",
    "Equestrian Studies",
    "European Studies",
    "Fashion",
    "Film",
    "Financial Services",
    "Fine Arts",
    "Food & Beverage",
    "Food Science",
    "Foreign Language",
    "Gay and Lesbian Studies",
    "Gender Studies",
    "Genetics",
    "Geography",
    "Graphic Design",
    "Health",
    "History",
    "Hospitality",
    "Human Biology",
    "Human Resources",
    "Human Services",
    "Industrial Engineering",
    "Information Technology",
    "Insurance",
    "Interior Design",
    "Journalism",
    "Journalism / News / Media",
    "Landscape Architecture",
    "Latin American Studies",
    "Latinx Studies",
    "Law",
    "Law / Legal Studies",
    "Library Science",
    "Management / Strategic Consulting",
    "Manufacturing",
    "Marine Sciences",
    "Maritime Studies",
    "Marketing",
    "Math",
    "Mechanical Engineering",
    "Medical Devices & Supplies",
    "Medicine",
    "Military",
    "Music",
    "Neurosciences",
    "Nursing",
    "Nutrition",
    "Performing Arts",
    "Pharmaceutical",
    "Philosophy",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Public Relations",
    "Publishing",
    "Real Estate",
    "Religion",
    "Social Work",
    "Sociology",
    "Software Engineering",
    "Sports",
    "Sports and Fitness",
    "Statistics",
    "Technology",
    "Telecommunications",
    "Theater",
    "Theology",
    "Tourism",
    "Transportation / Travel",
    "Urban Planning",
    "Urban Studies",
    "Visual Arts",
    "Women's Studies",
    "Writing",
  ]

  INTERESTS_OPTIONS = [INDUSTRIES_OPTIONS, STUDIES_OPTIONS].flatten.sort.uniq
end
