# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

def yaml label
  YAML.load(File.read("#{Rails.root}/db/seeds/#{label}.yml"))
end

if User.count == 0
  bz_admin = User.create! first_name: 'Dev', last_name: 'AdminBZ', email: 'admin@beyondz.org', password: "#{ENV['DEV_ENV_USER_PASSWORD']}", confirmed_at: DateTime.now
  bz_admin.add_role :admin
  bv_admin = User.create! first_name: 'Dev', last_name: 'AdminBV', email: 'admin@bebraven.org', password: "#{ENV['DEV_ENV_USER_PASSWORD']}", confirmed_at: DateTime.now
  bv_admin.add_role :admin
end

if PeerReviewQuestion.count == 0
  PeerReviewQuestion.create!(text: "Actively contributed to team success")
  PeerReviewQuestion.create!(text: "Met deadlines and fulfilled responsibilities in a timely manner")
  PeerReviewQuestion.create!(text: "Gave feedback to others to help them be more successful and productiver")
  PeerReviewQuestion.create!(text: "Embraced different perspectives on the team with openness and a sense of possibility")
end

if ChampionSearchSynonym.count == 0
  synonyms = [
    ["criminal justice", "criminology"],
    ["education", "childhood education"],
    ["art", "art history"],
    ["communications", "communication; minor psychology"],
    ["psychology", "communication; minor psychology"],
    ["communications", "training & development and organizational communication"],
    ["nonprofit", "non-profit/public/organizational management"],
    ["student services", "student services administration"],
    ["education", "student services administration"],
    ["human resources", "managerial and organizational behavior"],
    ["communications", "culture and communication"],
    ["liberal arts", "liberal arts and sciences/liberal studies"],
    ["criminal justice", "law"],
    ["criminal justice", "legal"],
    ["business", "general management"],
    ["math", "minor in mathematics"],
    ["lanuage", "american sign language"],
    ["education", "learning and instruction"],
    ["geography", "geographic information science and cartography"],
    ["doctor", "medical practice"],
    ["doctor", "health"],
    ["medicine", "health"],
    ["education", "learning"],
    ["finance", "venture capital"],
    ["political science", "government/plan i honors and spanish - hispanic studies"],
    ["politics", "political science"],
    ["education", "student affairs"],
    ["politics", "public policy"],
    ["politics", "government"],
    ["human resources", "employee benefits and compensation"],
    ["finance", "venture"],
    ["accountant", "accountancy"],
    ["psychology", "counseling"],
    ["business", "supply chain"],
    ["nonprofit", "non profit"],
    ["urban planning", "community and regional planning"],
    ["sociology", "social science"],
    ["human resources", "talent managements"],
    ["education", "college access"],
    ["human resources", "recruiting"],
    ["entrepreneur", "enterprise"],
    ["nonprofit", "non-profit"],
    ["criminal justice", "criminal/social justice"],
    ["criminal justice", "law school-juris doctorate"],
    ["engineer", "computer networking"],
    ["religion", "religious studies"],
    ["biology", "microbiology"],
    ["accountant", "accounting"],
    ["technology", "edtech"],
    ["education", "edtech"],
    ["actuary", "actuarial"],
    ["finance", "financial"],
    ["african american", "black studies"],
    ["african studies", "black studies"],
    ["business", "sales"],
    ["business", "mba/change mgmt"],
    ["neuro", "neurosciences"],
    ["software", "cyber security"],
    ["biology", "biotechnology studies"],
    ["pharmaceutical", "biotechnology studies"],
    ["journalism", "broadcast media"],
    ["education", "e-learning"],
    ["engineer", "software"],
    ["education", "primary/secondary"],
    ["business", "economics"],
    ["finance", "economics"],
    ["communications", "telecommunications"],
    ["computer science", "software engineer"],
    ["biology", "health"],
    ["nursing", "medicine"],
    ["public relations", "communications"],
    ["film", "media"],
    ["lawyer", "law"],
    ["cosmetics", "beauty"],
    ["public health", "health"],
    ["biotechnology", "pharmaceutical"],
    ["medical devices & supplies", "pharmaceutical"],
    ["biomedical engineering", "biotechnology"],
    ["biomedical engineering", "pharmaceutical"],
    ["criminology", "law"],
    ["criminology", "criminal justice"],
    ["digital media art", "design"],
    ["social media", "communications"],
    ["social media", "technology"],
    ["tourism", "hospitality"],
    ["visual arts", "art"],
    ["health policy", "health"],
    ["health policy", "political science"],
    ["policy", "politics"],
    ["international policy", "international studies"],
    ["international policy", "international development"],
    ["life coach", "therapy"],
    ["life coach", "counselor"],
    ["life coach", "psychology"],
    ["ecology", "environmental science"],
    ["marine biology", "environmental science"],
    ["ecology", "environmental studies"],
    ["marine biology", "environmental studies"],
    ["business development", "sales"],
    ["business development", "business"],
    ["machine learning", "data"],
    ["financial analyst", "financial services"],
    ["process engineer", "industrial engineering"],
    ["wellness", "health"],
    ["youth", "education"],
    ["nutrition", "health"],
    ["physical fitness", "fitness"],
    ["marketing research", "marketing"],
    ["child development", "early childhood"],
    ["sports and fitness", "fitness"],
    ["childcare", "education"],
    ["recruitment", "human resources"],
    ["recruitment", "human resources/employment"],
    ["renewable energy", "energy"],
    ["renewable energy", "environmental studies"],
    ["therapy", "psychology"],
    ["data science", "data"],
    ["anatomy", "human biology"],
    ["game development", "computer science"],
    ["biomedical engineering", "biotechnology"],
    ["premed", "health"],
    ["premed", "medicine"],
    ["web development", "software engineering"],
    ["web development", "computer science"],
    ["international affairs", "international studies"],
    ["advocacy", "nonprofit"],
    ["psychiatry", "psychology"],
    ["book publishing", "publishing"],
    ["latinx studies", "latin american studies"],
    ["nurse", "doctor"],
    ["dentist", "doctor"],
    ["women's studies", "women"],
    ["women's rights", "women"],
    ["feminism", "women"],
    ["women's studies", "women's studies"],
    ["gender studies", "women's studies"],
    ["data analysis", "data"],
    ["social worker", "social work"],
    ["grantwriting", "nonprofit"],
    ["culinary arts", "food"],
    ["sports management", "sports"],
    ["genetics", "biology"],
    ["police", "criminal justice"],
    ["programming", "computer science"],
    ["people operations", "human resources"],
  ]
  synonyms.each do |item|
    ChampionSearchSynonym.create!(search_term: item[0], search_becomes: item[1])
  end
end
